services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=flaskr
      - FLASK_ENV=development
    depends_on:
      - redis
      - mongo
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
